version: "3.9"

services:

  frontend:
    build: ./frontend
    container_name: catering_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: catering_backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: catering_db
      FLASK_SECRET_KEY: secret123
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: catering_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: catering_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/database_schema.sql:/docker-entrypoint-initdb.d/database_schema.sql

volumes:
  db_data:
